# Lets see if we can get this keep this repo size under the size limit
# The issue is these Allure reports take up too much space, even with them being deleted on each run
# That's because git still tracks deleted files, so we need to rewrite the history to remove them for good
# We need to test this out and see if it works, if there's any issues, or if we need further troubleshooting

name: Clean Repo History

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout full repo history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Check starting repo size on GitHub
        continue-on-error: true
        run: |
          size=$(curl -s "https://api.github.com/repos/${{ github.repository }}" | jq -r '.size')
          size_gb=$(echo "scale=3; $size / 1024 / 1024" | bc)
          echo "Repo size before cleanup: ${size_gb} GB"

      - name: Install BFG Repo-Cleaner
        run: |
          curl -L -o /tmp/bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.15.0/bfg-1.15.0.jar

      - name: Run BFG to delete all *.webm files
        run: |
          java -jar /tmp/bfg.jar --delete-files '*.webm'

      - name: Run git garbage collection
        run: |
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Force push all cleaned branches and tags
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin --force --all
          git push origin --force --tags

      - name: Check final repo size on GitHub
        continue-on-error: true
        run: |
          size=$(curl -s "https://api.github.com/repos/${{ github.repository }}" | jq -r '.size')
          size_gb=$(echo "scale=3; $size / 1024 / 1024" | bc)
          echo "Repo size after cleanup: ${size_gb} GB"
