# CAUTION: 🚨 This will rewrite the git history and remove .webm & .png files for good.
# WARNING: 💀 Once executed, the files are permanently deleted from the git history.

name: The Repo Clean-O-Matic (removes *.webm & *.png)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout full repo history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check starting repo size on GitHub
        continue-on-error: true
        run: |
          size=$(curl -s "https://api.github.com/repos/${{ github.repository }}" | jq -r '.size')
          size_mb=$(echo "scale=2; $size / 1024" | bc)
          size_gb=$(echo "scale=3; $size / 1024 / 1024" | bc)
          echo "Repo size before cleanup: ${size_mb} MB (or ${size_gb} GB if you prefer)"

      - name: Install BFG Repo-Cleaner
        run: |
          curl -L -o /tmp/bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.15.0/bfg-1.15.0.jar

      # Deleting .webm files with BFG Repo-Cleaner
      - name: Delete .webm files with BFG Repo-Cleaner
        run: java -jar /tmp/bfg.jar --delete-files '*.webm' --no-blob-protection

      # Deleting .png files with BFG Repo-Cleaner
      - name: Delete .png files with BFG Repo-Cleaner
        run: java -jar /tmp/bfg.jar --delete-files '*.png' --no-blob-protection

      - name: Git cleanup
        run: |
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
          git repack -a -d -f
          git prune-packed

      - name: Force push to GitHub
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin --all --force
          git push origin --force --tags

      - name: Upload BFG cleanup report files as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: bfg-cleanup-report
          path: /home/runner/work/playwright-allure-report/playwright-allure-report.bfg-report/*
          if-no-files-found: warn
          retention-days: 7

      # GitHub typically takes a while to update the repo.size, which can significantly delay testing changes to the script. 
      # This creates a challenge during QA testing, as it's hard to tell if any issues are due to the changes you made or simply
      # because the repo size hasn't updated yet. 
      # It becomes even trickier when multiple changes are made, as it’s difficult to pinpoint which one actually caused the size change! 
      # If you're tweaking the script, it's best to wait at least a full day before checking the size to avoid confusion.
      # Hopefully this will help you avoid the headache of trying to figure out if the script is working or if it's just GitHub being slow to update. LOL
      - name: Delayed update of GitHub repository size after cleanup
        run: |
          echo "The repository size probably won't update immediately after running this workflow."
          echo "GitHub's backend takes time to recalculate and reflect the updated repository size."
          echo "For smaller repositories or minor changes, the size update may happen within a few hours."
          echo "For larger repositories or significant history rewrites, it can take up to 1-2 days"
          echo "You can manually check it later with:"
          echo "curl -s https://api.github.com/repos/${{ github.repository }} | jq -r '.size'"
          echo "That'll return the size in KB. Divide by 1024 to get MB."
        