# CAUTION: 🚨 This will rewrite the git history and remove .webm & .png files for good.
# WARNING: 💀 Once executed, the files are permanently deleted from the git history.

name: The Repo Clean-O-Matic (removes *.webm & *.png)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout full repo history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check starting repo size on GitHub
        continue-on-error: true
        run: |
          size=$(curl -s "https://api.github.com/repos/${{ github.repository }}" | jq -r '.size')
          size_mb=$(echo "scale=2; $size / 1024" | bc)
          size_gb=$(echo "scale=3; $size / 1024 / 1024" | bc)
          echo "Repo size before cleanup: ${size_mb} MB (or ${size_gb} GB if you prefer)"

      - name: Install BFG Repo-Cleaner
        run: |
          curl -L -o /tmp/bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.15.0/bfg-1.15.0.jar

      # Deleting .webm files with BFG Repo-Cleaner in a separate step for reliability
      - name: Delete .webm files with BFG Repo-Cleaner
        run: java -jar /tmp/bfg.jar --delete-files '*.webm' --no-blob-protection

      # Deleting .png files with BFG Repo-Cleaner in a separate step for reliability
      - name: Delete .png files with BFG Repo-Cleaner
        run: java -jar /tmp/bfg.jar --delete-files '*.png' --no-blob-protection

      - name: Git cleanup
        run: |
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Add empty commit after BFG cleanup
        run: |
          git commit --allow-empty -m "Trigger cleanup push"

      - name: Force push to GitHub
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin --all --force
          git push origin --force --tags

      - name: Upload BFG cleanup report files as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: bfg-cleanup-report
          path: /home/runner/work/playwright-allure-report/playwright-allure-report.bfg-report/*
          if-no-files-found: warn
          retention-days: 7

      - name: Final note about repo size
        run: |
          echo "Note: GitHub repo size may take a while to update after cleanup."
          echo "You can manually check it later with:"
          echo "  curl -s https://api.github.com/repos/${{ github.repository }} | jq -r '.size'"
          echo "That'll return the size in KB. Divide by 1024 to get MB."
        
